const colors = {
  light: {
    text: "#0D0D18",
    tint: "#7C3AED",
    background: "#FAF9FF",
    foreground: "#0D0D18",
    card: "#FFFFFF",
    cardForeground: "#0D0D18",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#F3F0FF",
    secondaryForeground: "#1A1A2E",
    muted: "#F5F3FF",
    mutedForeground: "#6B6A8E",
    accent: "#EC4899",
    accentForeground: "#FFFFFF",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#E5E2FF",
    input: "#EDE9FF",
    surface: "#F8F6FF",
  },
  dark: {
    text: "#F0EFFF",
    tint: "#A855F7",
    background: "#0D0D18",
    foreground: "#F0EFFF",
    card: "#16162A",
    cardForeground: "#F0EFFF",
    primary: "#A855F7",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1E35",
    secondaryForeground: "#C8C7E8",
    muted: "#1A1A2F",
    mutedForeground: "#7B7A9E",
    accent: "#F472B6",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#252545",
    input: "#1E1E35",
    surface: "#13132A",
  },
  radius: 20,
};

export default colors;
